name: Build Moviepilot-Frontend Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release version
        id: release_version
        run: |
          frontend_version=$(jq -r '.version' package.json)
          echo "frontend_version=v$frontend_version" >> $GITHUB_ENV

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Build frontend
        id: build_frontend
        run: |
          yarn
          yarn build
          npm i -g pkg
          yarn pkg

      - name: Generate Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.frontend_version }}-win
          name: ${{ env.frontend_version }}-win
          draft: false
          prerelease: false
          files: |
            dist/MoviePilot-Frontend.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
